---
language: python
python: "3.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Symlink role name to repository
  - ln -s ansible-copr-reposync ../ganto.copr_reposync

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
