---

- name: Install required packages
  package:
    name: "{{ copr_reposync_packages }}"
    state: present

- name: Reposync user account
  user:
    name: "{{ copr_reposync_owner }}"
    home: "{{ copr_reposync_path.rstrip('/') }}"
    system: yes
    shell: /sbin/nologin

- name: Local path to store reposync mirrors
  file:
    path: '{{ copr_reposync_path }}'
    state: directory
    mode: 0755

- name: Repository directory and permissions
  file:
    path: '{{ copr_reposync_repo_path }}'
    state: directory
    mode: 0755
    owner: '{{ copr_reposync_owner }}'
    group: '{{ copr_reposync_owner }}'

- name: Reposync systemd service unit
  template:
    src: reposync@.service.j2
    dest: /etc/systemd/system/reposync@.service
    mode: 0644
    owner: root
    group: root

- name: Reposync systemd timer unit
  template:
    src: reposync@.timer.j2
    dest: /etc/systemd/system/reposync@.timer
    mode: 0644
    owner: root
    group: root
  when: copr_reposync_timer | bool

- name: Include tasks for repository mirror setup
  include_tasks: reposync_service.yml
  loop: '{{ copr_reposync_repos | difference(copr_reposync_remove_repos) | list }}'
  loop_control:
    loop_var: copr_reposync_include_repo

- name: Include tasks for repository mirror removal
  include_tasks: reposync_removal.yml
  loop: '{{ copr_reposync_remove_repos | list }}'
  loop_control:
    loop_var: copr_reposync_include_repo

- name: Download COPR repository GPG public key
  become: True
  become_user: '{{ copr_reposync_owner }}'
  get_url:
    url: '{{ copr_reposync_gpg_url }}'
    dest: '{{ copr_reposync_repo_path }}/'
    mode: 0644
  when: copr_reposync_gpg | bool

- name: Generate repo files for COPR mirror repositories
  become: True
  become_user: '{{ copr_reposync_owner }}'
  template:
    src: mirror.repo.j2
    dest: '{{ copr_reposync_repo_path }}/{{ copr_reposync_name | replace("/", "-") }}-{{ item }}.repo'
    mode: 0644
  when: copr_reposync_repofile | bool
  # get list of unique distributions from `copr_reposync_repos`
  with_items: '{{ lookup("template", "lookup/distributions.j2") }}'
