---

- name: Install required packages
  package:
    name: "{{ copr_reposync_packages }}"
    state: present

- name: Reposync user account
  user:
    name: "{{ copr_reposync_owner }}"
    home: "{{ copr_reposync_path.rstrip('/') }}"
    system: yes
    shell: /sbin/nologin

- name: Local path to store reposync mirrors
  file:
    path: '{{ copr_reposync_path }}'
    state: directory
    mode: 0755

- name: Repository directory and permissions
  file:
    path: '{{ copr_reposync_repo_path }}'
    state: directory
    mode: 0755
    owner: '{{ copr_reposync_owner }}'
    group: '{{ copr_reposync_owner }}'

- name: Reposync systemd service unit
  template:
    src: reposync@.service.j2
    dest: /etc/systemd/system/reposync@.service
    mode: 0644
    owner: root
    group: root

- name: Reposync systemd timer unit
  template:
    src: reposync@.timer.j2
    dest: /etc/systemd/system/reposync@.timer
    mode: 0644
    owner: root
    group: root
  when: copr_reposync_timer | bool

- name: Include tasks for distribution repository setup
  include_tasks: distribution.yml
  loop: '{{ copr_reposync_distributions | list }}'
  loop_control:
    loop_var: copr_reposync_include_distribution
