---
# copr_reposync_include_repo[0] = version
# copr_reposync_include_repo[1] = arch

- name: '{{ copr_reposync_include_distribution }}-{{ copr_reposync_include_repo[0] }}-{{ copr_reposync_include_repo[1] }} - Set repository fact'
  set_fact:
     copr_reposync_fact_repo: '{{ copr_reposync_include_distribution }}-{{ copr_reposync_include_repo[0] }}-{{ copr_reposync_include_repo[1] }}'

- name: '{{ copr_reposync_fact_repo }} - Set service name fact'
  set_fact:
     copr_reposync_fact_service: '{{ copr_reposync_service_name }}@{{ (copr_reposync_name.split("/"))[1] }}-{{ copr_reposync_fact_repo }}'

- name: '{{ copr_reposync_fact_repo }} - Create systemd service drop-in directory'
  file:
     path: '/etc/systemd/system/{{ copr_reposync_fact_service }}.service.d'
     state: directory
     mode: 0755
     owner: root
     group: root

- name: '{{ copr_reposync_fact_repo }} - Create systemd service configuration'
  template:
    src: override.conf.j2
    dest: '/etc/systemd/system/{{ copr_reposync_fact_service }}.service.d/override.conf'
    mode: 0644
    owner: root
    group: root
  register: copr_reposync_register_service

- name: '{{ copr_reposync_fact_repo }} - Define systemd service'
  file:
    path: '/etc/systemd/system/{{ copr_reposync_fact_service }}.service'
    src: '{{ copr_reposync_service_name }}@.service'
    state: link

- name: '{{ copr_reposync_fact_repo }} - Reload systemd'
  systemd:
    daemon_reload: '{{ copr_reposync_register_service is changed }}'
  when: (ansible_service_mgr | default('systemd')) == 'systemd'

- name: '{{ copr_reposync_fact_repo }} - Execute systemd service'
  systemd:
    name: '{{ copr_reposync_fact_service }}'
    state: started
    enabled: no
  when:
    - (copr_reposync_register_service is changed) or
      (copr_reposync_exec_sync | bool)
    - (ansible_service_mgr | default('systemd')) == 'systemd'

- name: '{{ copr_reposync_fact_repo }} - Include tasks to setup systemd timer'
  include_tasks: reposync_timer.yml
  when: copr_reposync_timer | bool
