---

- name: '{{ copr_reposync_fact_repo }} - Define systemd timer'
  file:
    path: '/etc/systemd/system/{{ copr_reposync_fact_service }}.timer'
    src: '{{ copr_reposync_service_name }}@.timer'
    state: link
  register: copr_reposync_register_timer

- name: '{{ copr_reposync_fact_repo }} - Enable systemd timer'
  systemd:
    name: '{{ copr_reposync_fact_service }}.timer'
    state: started
    enabled: yes
    daemon_reload: "{{ copr_reposync_register_timer is changed }}"
  when: ansible_service_mgr == 'systemd'
