---
# Copyright (C) 2021 Reto Gantenbein <reto.gantenbein@linuxmonk.ch>
# SPDX-License-Identifier: Apache-2.0

- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    # Install apache2 to server repository mirror
    - name: Install Apache2 httpd server
      package:
        name: httpd
        state: present

    - name: Enable and start httpd service
      systemd:
        enabled: true
        name: httpd.service
        state: started
      register: prepare_httpd
      failed_when: false

    - name: Check journald logs  # noqa no-changed-when
      shell: echo httpd.service ; systemctl cat httpd.service ; journalctl -u httpd.service ; echo httpd-init.service ; systemctl cat httpd-init.service ; journalctl -u httpd-init.service
      register: prepare_journald

    - name: Show journald logs
      debug:
        var: prepare_journald.stdout_lines
